### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

array = np.random.randint(1, 51, size = 10)
print(array)
media = np.mean(array)
print("Media ", media)
dvp = np.std(array)
print("desvio padrão", dvp)

[33 38 29 46  4 32 50  3  6 42]
Media  28.3
desvio padrão 16.822901057784296


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
import numpy as np

array = np.random.rand(10)
print(array)
for i in array:
  if i <= 0.5:
    raiz = np.sqrt(i)
    print(raiz)

[0.54013427 0.91440645 0.8265625  0.1268216  0.61127001 0.54368765
 0.42754074 0.28820549 0.03452901 0.82518966]
0.3561202054147303
0.6538659984746907
0.5368477305960441
0.1858198452291503


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np

matriz = np.random.rand(3, 3, 3)
print("matriz", matriz)
v_max = np.amax(matriz, axis =1)
print("2d",v_max)


matriz [[[0.23299371 0.92636782 0.87088729]
  [0.31205518 0.89820067 0.90039003]
  [0.35517339 0.90940309 0.01893999]]

 [[0.31298118 0.87694827 0.54390832]
  [0.32612839 0.10188221 0.79322523]
  [0.29627622 0.41356613 0.92958482]]

 [[0.17676543 0.49549399 0.13450866]
  [0.97881584 0.91314841 0.23602096]
  [0.05527646 0.70018267 0.79796919]]]
2d [[0.35517339 0.92636782 0.90039003]
 [0.32612839 0.87694827 0.92958482]
 [0.97881584 0.91314841 0.79796919]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
import numpy as np

matriz = np.random.rand(5, 5)
print("matriz", matriz)
media = np.mean(matriz, axis = 1)
print("media", media)
sub_media = matriz - media[:, np.newaxis]
print("sub_media",sub_media)

matriz [[0.46760165 0.97343985 0.57530172 0.54383358 0.51882905]
 [0.36665239 0.96323815 0.33655137 0.16244944 0.56830307]
 [0.24263268 0.03320224 0.39091105 0.44486902 0.80779865]
 [0.20410553 0.92484054 0.63197382 0.28844112 0.31657545]
 [0.46586248 0.85703369 0.81436802 0.64827668 0.20498409]]
media [0.61580117 0.47943888 0.38388273 0.47318729 0.59810499]
sub_media [[-0.14819952  0.35763868 -0.04049945 -0.07196759 -0.09697212]
 [-0.1127865   0.48379927 -0.14288752 -0.31698945  0.08886419]
 [-0.14125005 -0.35068049  0.00702832  0.06098629  0.42391592]
 [-0.26908176  0.45165325  0.15878652 -0.18474617 -0.15661184]
 [-0.13224252  0.2589287   0.21626303  0.05017169 -0.3931209 ]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np

matriz = np.random.rand(4, 4)
print("matriz", matriz)
diag_prin = np.diag(matriz)
diag_sec = np.diag(np.fliplr(matriz))

print("diagonal", diag_prin)
print("diagonal", diag_sec)
media_diag = np.mean([diag_prin, diag_sec])
print("media diagonal",media_diag)
dvp_diag = np.std([diag_prin, diag_sec])
print("desvio padrão diagonal",dvp_diag)

matriz [[0.16424957 0.24487409 0.43716022 0.24576284]
 [0.76478463 0.48928164 0.76527943 0.44628043]
 [0.12476127 0.68152044 0.44542948 0.53275836]
 [0.56527062 0.34341365 0.17865882 0.62994669]]
diagonal [0.16424957 0.48928164 0.44542948 0.62994669]
diagonal [0.24576284 0.76527943 0.68152044 0.56527062]
media diagonal 0.49834258975100454
desvio padrão diagonal 0.19522582245592854
